name: vase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.1
  dio: ^5.5.0+1
  card_swiper: ^3.0.1
  fl_chart: ^0.68.0
  flutter_blue_plus: ^1.32.11
  fluttertoast: ^8.2.6
  scan: ^1.6.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - images/icon.png
   - images/flower.png